"use client"

// Plugin-contributed components that may be used standalone
export * from "./components/auth/magic-link"
export * from "./components/delete-user/danger-zone"
export * from "./components/delete-user/delete-user"
export * from "./components/multi-session/manage-account"
export * from "./components/multi-session/manage-accounts"
export * from "./components/multi-session/switch-account-submenu"
export * from "./components/multi-session/switch-account-submenu-content"
export * from "./components/multi-session/switch-account-submenu-item"
export * from "./components/passkey/passkeys"
export * from "./components/theme/appearance"
export * from "./components/theme/theme-toggle-item"
export * from "./components/username/sign-in-username"
export * from "./components/username/username-field"
export * from "./lib/auth-plugin"
export * from "./lib/delete-user/delete-user-plugin"
export * from "./lib/magic-link/magic-link-plugin"
export * from "./lib/multi-session/multi-session-plugin"
export * from "./lib/passkey/passkey-plugin"
export * from "./lib/theme/theme-plugin"
export * from "./lib/username/username-plugin"
